---
abstract: 'Provides the ability to hook functions to the starting and stopping of the screen saver (Linux only at the moment)'
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Event-ScreenSaver
provides:
  Event::ScreenSaver:
    file: lib/Event/ScreenSaver.pm
    version: v0.0.2
  Event::ScreenSaver::Unix:
    file: lib/Event/ScreenSaver/Unix.pm
    version: v0.0.1
requires:
  List::MoreUtils: 0
  Module::Build: 0
  Moose: 0
  Pod::Usage: 0
  Test::More: 0
  Test::NoWarnings: 0
  perl: 5.006
  version: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Event-ScreenSaver
  license: http://dev.perl.org/licenses/
  repository: http://github.com/ivanwills/Event-ScreenSaver
version: v0.0.2
